### ISSUE TITLE
Transaction getting reverted on minting the wrapped document on v5.1.0

### ISSUE THREAD

**Issue by manishraana** [TradeTrust/token-registry#45]
Hi Team, 

We were using version @tradetrust/token-registry version 4 and it was working fine.
Now we are upgrading to latest version v5.1.0 with ethers v5, but transaction getting reverted

When we are minting the document it is not working, transaction execution is getting reverted.
We are trying it on stability.

We have updated the schema as well and the schema validation is getting validated as true.

We have also tried using @trustvc/trustvc, but that is also not helping.

we are using the same rpc on v4 and it was working fine on v4.

can you let us know about any know issues with v5 so we can try finding a workaround for this.
Is there any existing react implementation for the same package ? 

![error](https://github.com/user-attachments/assets/c6730fb3-61d3-49ea-96cd-72c0c0fd60f5)

**Comment by nghaninn** [comment]
Hi @manishraana 

just notice your issue. Is it possible to provide a code snippet? or for which smart contract function are you interacting with.

Thanks

**Comment by nghaninn** [comment]
Hi @manishraana 

You are calling the correct mint function signature from token registry v5.
the fields that you have provided to the mint functions were correct, inline with the our tested mint in polygon.
```
0x6010a5e7
000000000000000000000000773060d0bb516587cfe0490e2077c285870b826e
000000000000000000000000773060d0bb516587cfe0490e2077c285870b826e
4324c06aa42bd2ac0ba3baf121843ac4978e77ee51856292beb8f6c974994838
0000000000000000000000000000000000000000000000000000000000000080
0000000000000000000000000000000000000000000000000000000000000000
```
https://amoy.polygonscan.com/tx/0x71ce1e7a3a8d351decc7740c14e87726680757d5029963a411253985536bec57

______

However, I notice that you are interacting with the smart contract [`0xa142aeEBd17Fdc685e5BaD09C5b7f37D5210Dc08`](https://stability.blockscout.com/address/0xa142aeEBd17Fdc685e5BaD09C5b7f37D5210Dc08?tab=txs), which has been created within `0xcd4d27b7c25F57D8121F6E8fdc668b6AA9a212a9` address, using `0x773060D0BB516587cFE0490e2077c285870B826e` address.

Can i confirm that there's an oversight on this? 

If this is intentional, you will need to look into [Roles and Access](https://github.com/TradeTrust/token-registry?tab=readme-ov-file#roles-and-access) control, to allow non smart contract creator addresses to interact with the contract.
